export const FETCH_RECIPE_DATA_START = "FETCH_RECIPE_DATA_START"
export const FETCH_RECIPE_DATA_SUCCESS = "FETCH_RECIPE_DATA_SUCCESS"
export const FETCH_RECIPE_DATA_FAIL = "FETCH_RECIPE_DATA_FAIL"

export const GET_CHOSEN_RECIPE_START = "GET_CHOSEN_RECIPE_START"
export const GET_CHOSEN_RECIPE_SUCCESS = "GET_CHOSEN_RECIPE_SUCCESS"

export const MOVE_ITEM_ING_TO_SHOP_LIST_START = "MOVE_ITEM_ING_TO_SHOP_LIST_START"
export const MOVE_ITEM_ING_TO_SHOP_LIST_SUCCESS = "MOVE_ITEM_ING_TO_SHOP_LIST_SUCCESS"
export const DELETE_SHOPPING_ING_SUCCESS = "DELETE_SHOPPING_ING_SUCCESS"

export const OLD_ING_LIST_SHOW_START = "OLD_ING_LIST_SHOW_START"
export const OLD_ING_LIST_SHOW_SUCCESS = "OLD_ING_LIST_SHOW_SUCCESS"

export const MOVE_ITEM_TO_LIKES_SUCCESS = "MOVE_ITEM_TO_LIKES_SUCCESS"
export const REMOVE_ITEM_LOCAL_SUCCESS = "REMOVE_ITEM_LOCAL_SUCCESS"
export const DISPLAY_CHOSEN_LIKE_ITEM_SUCCESS = "DISPLAY_CHOSEN_LIKE_ITEM_SUCCESS"

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
export const AUTH_LOGOUT_CLEAR = "AUTH_LOGOUT_CLEAR"

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH"

export const SEND_ITEM_TO_SERVER_START = "SEND_ITEM_TO_SERVER_START"
export const SEND_ITEM_TO_SERVER_SUCCESS = "SEND_ITEM_TO_SERVER_SUCCESS"
export const SEND_ITEM_TO_SERVER_FAIL = "SEND_ITEM_TO_SERVER_FAIL"

export const FETCH_LIKES_ITEMS_FROM_SERVER_START = "FETCH_LIKES_ITEMS_FROM_SERVER_START"
export const FETCH_LIKES_ITEMS_FROM_SERVER_SUCCESS = "FETCH_LIKES_ITEMS_FROM_SERVER_SUCCESS"
export const FETCH_LIKES_ITEMS_FROM_SERVER_FAIL = "FETCH_LIKES_ITEMS_FROM_SERVER_FAIL"

export const REMOVE_ITEM_IN_SERVER_START = "REMOVE_ITEM_IN_SERVER_START"
export const REMOVE_ITEM_IN_SERVER_SUCCESS = "REMOVE_ITEM_IN_SERVER_SUCCESS"
export const REMOVE_ITEM_IN_SERVER_FAIL = "REMOVE_ITEM_IN_SERVER_FAIL"
