export const FETCH_RECIPE_DATA_SAGA = 'FETCH_RECIPE_DATA_SAGA';
export const FETCH_RECIPE_DATA_SUCCESS = 'FETCH_RECIPE_DATA_SUCCESS';
export const FETCH_RECIPE_DATA_FAIL = 'FETCH_RECIPE_DATA_FAIL';

export const GET_CHOSEN_RECIPE_SAGA = 'GET_CHOSEN_RECIPE_SAGA';
export const GET_CHOSEN_RECIPE_SUCCESS = 'GET_CHOSEN_RECIPE_SUCCESS';

export const MOVE_ITEM_ING_TO_SHOP_LIST_SAGA = 'MOVE_ITEM_ING_TO_SHOP_LIST_SAGA';
export const MOVE_ITEM_ING_TO_SHOP_LIST_SUCCESS = 'MOVE_ITEM_ING_TO_SHOP_LIST_SUCCESS';

export const DELETE_SHOPPING_ING_SAGA = 'DELETE_SHOPPING_ING_SAGA';
export const DELETE_SHOPPING_ING_SUCCESS = 'DELETE_SHOPPING_ING_SUCCESS';

export const OLD_ING_LIST_SHOW_SAGA = 'OLD_ING_LIST_SHOW_SAGA';
export const OLD_ING_LIST_SHOW_SUCCESS = 'OLD_ING_LIST_SHOW_SUCCESS';

export const MOVE_ITEM_TO_LIKES_SAGA = 'MOVE_ITEM_TO_LIKES_SAGA';
export const MOVE_ITEM_TO_LIKES_SUCCESS = 'MOVE_ITEM_TO_LIKES_SUCCESS';
export const REMOVE_ITEM_LOCAL_SAGA = 'REMOVE_ITEM_LOCAL_SAGA';
export const REMOVE_ITEM_LOCAL_SUCCESS = 'REMOVE_ITEM_LOCAL_SUCCESS';
export const DISPLAY_CHOSEN_LIKE_ITEM_SAGA = 'DISPLAY_CHOSEN_LIKE_ITEM_SAGA';
export const DISPLAY_CHOSEN_LIKE_ITEM_SUCCESS = 'DISPLAY_CHOSEN_LIKE_ITEM_SUCCESS';

export const AUTH_SAGA = 'AUTH_SAGA';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_CHECK_TIMEOUT_SAGA = 'AUTH_CHECK_TIMEOUT_SAGA';
export const AUTH_FAIL = 'AUTH_FAIL';

export const AUTH_CHECK_STATE_SAGA = 'AUTH_CHECK_STATE_SAGA';

export const AUTH_LOGOUT_SAGA = 'AUTH_LOGOUT_SAGA';
export const AUTH_LOGOUT_SUCCEED = 'AUTH_LOGOUT_SUCCEED';
export const AUTH_LOGOUT_CLEAR_SAGA = 'AUTH_LOGOUT_CLEAR_SAGA';
export const AUTH_LOGOUT_CLEAR = 'AUTH_LOGOUT_CLEAR';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SEND_ITEM_TO_SERVER_SAGA = 'SEND_ITEM_TO_SERVER_SAGA';
export const SEND_ITEM_TO_SERVER_SUCCESS = 'SEND_ITEM_TO_SERVER_SUCCESS';
export const SEND_ITEM_TO_SERVER_FAIL = 'SEND_ITEM_TO_SERVER_FAIL';

export const FETCH_LIKES_ITEMS_FROM_SERVER_SAGA = 'FETCH_LIKES_ITEMS_FROM_SERVER_SAGA';
export const FETCH_LIKES_ITEMS_FROM_SERVER_SUCCESS = 'FETCH_LIKES_ITEMS_FROM_SERVER_SUCCESS';
export const FETCH_LIKES_ITEMS_FROM_SERVER_FAIL = 'FETCH_LIKES_ITEMS_FROM_SERVER_FAIL';

export const REMOVE_ITEM_IN_SERVER_SAGA = 'REMOVE_ITEM_IN_SERVER_SAGA';
export const REMOVE_ITEM_IN_SERVER_SUCCESS = 'REMOVE_ITEM_IN_SERVER_SUCCESS';
export const REMOVE_ITEM_IN_SERVER_FAIL = 'REMOVE_ITEM_IN_SERVER_FAIL';
